baseURL = 'https://tews.dev/'
languageCode = 'de-de'
title = 'tews.dev'

[params]
[params.author]
name = 'Michael Tews'
title = 'Softwareentwickler'
github = 'https://github.com/mewsen'
pgp = 'A097DD3ACE709315A86D6EE10512FA62963CFD20'
email = 'michael@tews.dev'

[markup]
[markup.highlight]
noClasses = false

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[module]
[module.hugoVersion]
extended = false
min = "0.116.0"
