name = 'min'
license = 'MIT'
licenselink = 'https://github.com/mewsen/min/LICENSE'
description = 'My minimalistic monochrome Hugo theme'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/mewsen/min'

# If you have a running demo of the theme
demosite = 'https://mewsen.github.io/min'

# Taxonomy terms
tags = ['blog', 'company']
features = ['some', 'awesome', 'features']

# If the theme has a single author
[author]
name = 'Michael Tews'
homepage = 'tews.dev'
